version: "3"
services:
  hub:
    image: selenium/hub:latest
  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:latest
    shm_size: '512m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: raghavkjdocker/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output
  book-flight-module:
    image: raghavkjdocker/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./output/book-result:/usr/share/udemy/test-output